### ISSUE TITLE
jstify transform problem

### ISSUE THREAD

**Issue by hugomrdias** [royriojas/persistify#3] opened 2015-11-03 12:41 UTC
cant get jstify to work, it gives a ParseError: Unexpected token on the first .tpl file.

``` js
gulp.task('js2', function() {
    var persistify = require('persistify');

    var b = persistify({
        //entries:   ['./app/scripts/main.js'],
        debug:     true,
        fullPaths: true,
    }, {watch: false});

    b.add('./app/scripts/main.js');
    b.transform('jstify', {
        engine:       'lodash',
        templateOpts: {
            variable: 'data'
        }
    });

    // Externals
    libs.forEach(function(lib) {
        b.external(lib);
    });

    b.on('bundle:done', function(time) {
        console.log('time', time);
    });

    b.on('error', function(err) {
        console.log('error', err);
    });

    b.on('update', function() {
        doBundle();
    });

    function doBundle() {
        return b
            .bundle()
            .on('error', utils.handleError)
            .pipe(source('app.js'))
            .pipe(buffer())
            .pipe(sourcemaps.init({loadMaps: true}))
            .pipe(frep(config.replace.config))
            .pipe(sourcemaps.write('.', {includeContent: false, sourceRoot: '.'}))
            .pipe(gulp.dest(global.destFolder + '/scripts'))
            .pipe(size({title: 'JS       '}));
    }

    return doBundle();
});

```

**Comment by royriojas** [comment] 2015-11-03 15:02
Hi @hugomrdias, can you provide a sample of the `.tpl` file that is failing?

Also if you replace `persistify` with `browserify`, does it works?

Regards

**Comment by royriojas** [comment] 2016-01-24 22:00
I'm closing this issue as I cannot reproduce it. Please feel free to reopen if you have more info

**Closed as completed by royriojas** 2016-01-24 22:00 UTC
