### ISSUE TITLE
Cannot parse cache on ec2 instance

### ISSUE THREAD

**Issue by kasbah** [royriojas/persistify#8] opened 2016-03-09 19:46 UTC
I am trying to run a build on an ec2 instance running Ubuntu 14.04 64-bit. I have been running this build ok on a local 64-bit Ubuntu machine. The problems I get are related to the cache:

```
persistify --extension='.jsx' --transform [ babelify --presets [ react es2015 ] ] --debug -x react -x react-dom build/.temp/boards/github.com/kitnic/RiftDK1/render_page.jsx -o build/boards/github.com/kitnic/RiftDK1/app.js
undefined:1
{"configHash":3703766225,"persistifyArgs":{"cache":{"/home/ubuntu/kitnic/build/.temp/boards/github.com/kitnic/Bus_Pirate/info.json":{"source":"{\"id\":\"github.com/kitnic/Bus_Pirate\",\"description\":\"The Bus Pirate is an open source hacker multi-tool that talks to electronic stuff.\",\"site\":\"http://dangerousprototypes.com/docs/Bus_Pirate\",\"bom\":[{\"reference\":\"C1-C6\",\"quantity\":6,\"description\":\"\",\"partNumbers\":[\"Kemet C0603C104K5RACTU\"],\"retailers\":{\"Digikey\":\"399-5089-1-ND\",\"Mouser\":\"80C0603C104K5R\",\"RS\":\"7738601\",\"Newark\":\"72J5992\",\"Farnell\":\"1288255\"},\"row\":11},{\"reference\":\"C7,C8,C9\",\"quantity\":3,\"description\":\"\",\"partNumbers\":[\"Kemet C0603C105Z8VACTU\"],\"retailers\":{\"Digikey\":\"399-3216-1-ND\",\"Mouser\":\"80C0603C105Z8V\",\"RS\":\"5158479\",\"Newark\":\"84K8389\",\"Farnell\":\"2522398\"},\"row\":11},{\"reference\":\"C10,C11\",\"quantity\":2,\"description\":\"\",\"partNumbers\":[\"Sprague 293D106X0010A2TE3\",\"Vishay 293D106X96R3

SyntaxError: Unexpected number
    at Object.parse (native)
    at readJsonSync (/home/ubuntu/kitnic/node_modules/read-json-sync/index.js:10:15)
    at Object.cache.load (/home/ubuntu/kitnic/node_modules/flat-cache/cache.js:25:23)
    at Object.module.exports.create (/home/ubuntu/kitnic/node_modules/flat-cache/cache.js:157:9)
    at Object.module.exports.load (/home/ubuntu/kitnic/node_modules/flat-cache/cache.js:143:17)
    at module.exports (/home/ubuntu/kitnic/node_modules/persistify/index.js:31:25)
    at run (/home/ubuntu/kitnic/node_modules/persistify/bin/cmd.js:25:27)
    at Object.<anonymous> (/home/ubuntu/kitnic/node_modules/persistify/bin/cmd.js:117:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

I think the relevant cache file is this: https://gist.github.com/kasbah/371ed82eba3f236775fd.  If you run this through http://jsonlint.com you can see that there is a problem. 

All of this is for my project at https://github.com/monostable/kitnic

**Comment by kasbah** [comment] 2016-03-09 19:52
It doesn't seem to be running out of RAM either (checked with htop).

**Comment by royriojas** [comment] 2016-04-14 15:46
hi @kasbah 

mm, sorry for the long time to reply,

Do you have a reduced test case that I can use to reproduce this issue?

**Comment by royriojas** [comment] 2016-07-26 18:39
closing this for now, since I have not a way to replicate this issue. Feel free to reopen if this is still an issue.

**Closed as completed by royriojas** 2016-07-26 18:39 UTC
